version: '2'
services:
  seed:
    image: mhamrah/clustering:0.3
    environment:
      CLUSTER_PORT: 1600
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed

  c1:
    image: mhamrah/clustering:0.3
    environment:
      CLUSTER_PORT: 0
      CLUSTER_IP: ""
      SEED_PORT_1600_TCP_ADDR: seed

